Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'
urlpatterns = [
    path('', views.index, name='index'),
    path('details/<movie_id>/', views.details, name='details'),
    path('ajax/like/', views.post_like, name='post_like'),
    path('ajax/dislike/', views.post_dislike, name='post_dislike'),

]

MovieAPI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Home.urls')),
    path('admin/', admin.site.urls),
]

Home/models.py
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=100, blank=False)
    id = models.CharField(blank=False, primary_key=True, max_length=10)
    thumbsUp = models.IntegerField(default=0)
    thumbsDown = models.IntegerField(default=0)

    Movies = models.Manager()

    def __str__(self):
        return self.title

Home/forms.py
from .models import Movie
from django import forms


class SearchForm(forms.Form):
    search_movie = forms.CharField(max_length=100)

Home/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .forms import SearchForm
from .models import Movie
from .api_service import APIService


def index(request):
    """
    Main Home Page function. Returns searched movie on same page.
    """
    movie = SearchForm(request.POST or None)
    context = {
        'movie': movie,
        'results': [],
        'rating': []
    }
    if request.method == 'POST':
        if 'search_movies' in request.POST:  # Checks to see if the request includes 'search_movie'
            search_results = api_request(request)  # Gets info from API for movie search
            for i in search_results:  # looping through API results
                if get_ratings(i['id']):  # Checks to see if search result exists in db
                    i['rating'] = get_ratings(i['id'])
                context['results'].append(i)
            return render(request, 'Home/home.html', context)

    return render(request, 'Home/home.html', context)


def details(request, movie_id):
    """
    Gets Movie details by searching movie id with API
    """
    api = APIService()
    movie_details = api.get_details(movie_id)  # Gets movie details using movie unique ID
    context = {
        'details': movie_details,
    }
    return render(request, 'Home/details.html', context)


def api_request(request):
    """
    Returns response from API
    """
    api = APIService()
    title = request.POST.get('search_movie', False)  # Gets movie searched from request
    res = api.search_title(title)  # Searches API for movie using movie title
    return res


def get_ratings(movie_id):
    """
    Returns rating for movie if movie exists in db
    """
    if Movie.Movies.filter(pk=movie_id).exists():  # Checks db for existing movie entry to get likes and dislikes count
        movie = Movie.Movies.get(pk=movie_id)  # Gets likes and dislikes from db for movie
        rating = {
            'likes': movie.thumbsUp,
            'dislikes': movie.thumbsDown,
            'movie_id': movie_id,
        }
        return rating
    else:
        return False


def post_like(request):
    """
    Handles AJAX request for like button

    Returns Thumbs up count
    """
    if request.is_ajax() and request.method == 'POST':
        movie_id = request.POST.get('movie_id')
        movie_title = request.POST.get('movie_title')
        movie_likes = request.POST.get('likes')

        obj, created = Movie.Movies.update_or_create(
            pk=movie_id, defaults={'title': movie_title, 'thumbsUp': int(movie_likes) + 1})

        return HttpResponse(obj.thumbsUp)
    else:
        return HttpResponse('unsuccessful')


def post_dislike(request):
    """
    Handles AJAX request for dislike button

    Returns Thumbs Down count
    """
    if request.is_ajax() and request.method == 'POST':
        movie_id = request.POST.get('movie_id')
        movie_title = request.POST.get('movie_title')
        movie_dislikes = request.POST.get('dislikes')

        # Updates or creates db entry
        obj, created = Movie.Movies.update_or_create(
            pk=movie_id, defaults={'title': movie_title, 'thumbsDown': int(movie_dislikes) + 1})

        return HttpResponse(obj.thumbsDown)
    else:
        return HttpResponse('unsuccessful')

templates/Home/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ details.title }}{% endblock %}
{% block content %}
    <div class="details-background-container">
        <img class="backgroundImage details-background" src="{{ details.poster }}" alt="Movie Poster">
    </div>
    <a class="back-button" onclick="back()">
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
        </svg>
    </a>
    <div class="container-fluid top-details-container">
        <div class="row">
            <div class="col-md-8">
                <div class="title-box">
                    <h1>{{ details.title }}</h1>
                </div>
                <div class="row">
                    <div class="col-4 cast-box">
                        <h4>Cast</h4>
                        <ul class="cast-list-before">
                            {% for actor in details.cast|slice:"5" %}
                                <li>{{ actor.actor }}<br></li>
                            {% endfor %}
                        </ul>
                        <ul class="cast-list-after">
                            {% for actor in details.cast %}
                                <li id="cast-character">- {{ actor.character }}</li>
                                <li>{{ actor.actor }}</li><br>
                            {% endfor %}
                        </ul>
                        <a class="more" onclick="more()">More</a>
                        <a class="less" onclick="less()">Less</a>
                    </div>
                    <div class="col-8">
                        <div class="info-box">
                            <p>{{ details.length }}</p>
                            <p>{{ details.year }}</p>
                        </div>
                        {{ details.plot }}
                    </div>
                </div>
            </div>
            <div class="col-md-4 poster-container">
                <div class="col-12 details-poster-info">
                    <img class="movie-poster" src="{{ details.poster }}" alt="Movie Poster" width="250px" height="400px">
                </div>
                <div class="col-12 details-poster-info">
                    <a class="btn btn-secondary trailer-button" href="{{ details.trailer.link }}" target="_blank">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-file-play-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM6 5.883v4.234a.5.5 0 0 0 .757.429l3.528-2.117a.5.5 0 0 0 0-.858L6.757 5.454a.5.5 0 0 0-.757.43z"/>
                        </svg>
                        Watch Trailer
                    </a>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/Home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Movie Finder{% endblock %}
{% block content %}
<div class="container">
    <div class="backgroundImage">
        <img class="backgroundImage" src="{% static './images/movieTitlesVignette.jpg' %}" alt="Background Image">
    </div>
    <div id="input_container">
        <form method="post" id="input_form">
            {% csrf_token %}
            <table>
                {{ movie.as_p }}
            </table>
            <button class="btn btn-secondary searchButton" type="submit" name="search_movies">Search</button>
        </form>
    </div>
    <div id="movie_container">
        <div>
            {% for movie in results %}
                <div class="card">
                    <div class="card-header">
                        <h1 id="movie_title">{{ movie.title }}</h1>
                    </div>
                    <div class="card-body">
                        <img src="{{ movie.image }}" alt="Movie Image" height="400px" width="250px">
                    </div>
                    <div class="card-footer">
                        <div class="details-container">
                            <a class="btn btn-secondary" href="{% url 'Home:details' movie.id %}">Details</a>
                        </div>
                        <div class="like-container">
                            <form method="POST" id="like-form">
                                {% csrf_token %}
                                <button class="like btn btn-primary" type="submit" value="{{ movie.id }}" id="like{{ movie.id }}">
                                    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg>
                                    {% if movie.rating %}
                                        <div class="movie_like_count{{ movie.id }}">{{ movie.rating.likes }}</div>
                                    {% else %}
                                        <div class="movie_like_count{{ movie.id }}">0</div>
                                    {% endif %}
                                </button>
                            </form>
                            <form method="POST" id="dislike-form">
                                {% csrf_token %}
                                <button class="dislike btn btn-danger" type="submit" value="{{ movie.id }}" id="dislike{{ movie_id }}">
                                    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28v1c.563 0 .901.272 1.066.56.086.15.121.3.121.416 0 .12-.035.165-.04.17l-.354.353.353.354c.202.202.407.512.505.805.104.312.043.44-.005.488l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.415-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.353.352.373.714.267 1.021-.122.35-.396.593-.571.651-.653.218-1.447.224-2.11.164a8.907 8.907 0 0 1-1.094-.17l-.014-.004H9.62a.5.5 0 0 0-.595.643 8.34 8.34 0 0 1 .145 4.725c-.03.112-.128.215-.288.255l-.262.066c-.306.076-.642-.156-.667-.519-.075-1.081-.239-2.15-.482-2.85-.174-.502-.603-1.267-1.238-1.977C5.597 8.926 4.715 8.23 3.62 7.93 3.226 7.823 3 7.534 3 7.28V3.279c0-.26.22-.515.553-.55 1.293-.138 1.936-.53 2.491-.869l.04-.024c.27-.165.495-.296.776-.393.277-.096.63-.163 1.14-.163h3.5v-1H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                                    </svg>
                                    {% if movie.rating %}
                                        <div class="movie_dislike_count{{ movie.id }}">{{ movie.rating.dislikes }}</div>
                                    {% else %}
                                        <div class="movie_dislike_count{{ movie.id }}">0</div>
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/Home/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search Titles{% endblock %}
{% block content %}
    <h2>Search Page</h2>
    {{ title }}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Internal CSS -->
    <link rel="stylesheet" type="text/css" href="{% static './css/main.css' %}">
</head>
<body>
<div class="container-fluid base-container">
    {% block content %}{% endblock %}
</div>
</body>

<!-- Bootstrap jQuery and JS bundle w/ Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Internal JS -->
<script src="{% static './js/main.js' %}"></script>

{% block javascript %}{% endblock %}
</html>